
POST http://localhost:4000/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "1pos@gmail.com",
  "password": "123456"
}

###

## Register
POST http://localhost:4000/user/register HTTP/1.1
Content-Type: application/json

{
  "email":"bordnik@gmail.com",
  "name":"Aleks",
  "userType":true,
  "password":"123456dfd"
}

###

##Update
POST http://localhost:4000/user/update/6496426386fbd81395dc25c9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY0OTY0MjYzODZmYmQ4MTM5NWRjMjVjOSIsImVtYWlsIjoiMXBvc0BnbWFpbC5jb20iLCJpYXQiOjE2ODgxODcwMTYsImV4cCI6MTY4ODM1OTgxNn0.x-jrLRKpBeJqDRVB80_cUUMxKgto95E7KLq8Yg_OnKU

{
  "name":"Aleks",

  "avatarPath":"gold.png"
}

###
## avatar loading
POST http://localhost:4000/user/6496426386fbd81395dc25c9/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY0OTY0MjYzODZmYmQ4MTM5NWRjMjVjOSIsImVtYWlsIjoiMXBvc0BnbWFpbC5jb20iLCJpYXQiOjE2ODgxODcwMTYsImV4cCI6MTY4ODM1OTgxNn0.x-jrLRKpBeJqDRVB80_cUUMxKgto95E7KLq8Yg_OnKU
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /home/bordnik/Изображения/Снимок экрана.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
###

## token verification
GET http://localhost:4000/user/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY0OTY0MjYzODZmYmQ4MTM5NWRjMjVjOSIsImVtYWlsIjoiMXBvc0BnbWFpbC5jb20iLCJpYXQiOjE2ODgxODcwMTYsImV4cCI6MTY4ODM1OTgxNn0.x-jrLRKpBeJqDRVB80_cUUMxKgto95E7KLq8Yg_OnKU
###
