# find
GET http://localhost:4000/offers/10 HTTP/1.1
###
# show
GET http://localhost:4000/64a23eb427c6a4e8e1550203 HTTP/1.1
###

# create
POST http://localhost:4000/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY0YTEzZWQ4ZDA0YjYxNzlhMmNmZDI3MSIsImVtYWlsIjoiMXRvcnRAZ21haWwuY29tIiwiaWF0IjoxNjg4MzUyOTI3LCJleHAiOjE2ODg1MjU3Mjd9.30aBkIT3Mkw-fPvMnEcMrl0YHHfOGih_ZQDk85NiU1I

{
  "offerName": "Сдам Дом у Озера",
  "description": "Очень красивый Микрорайон Любимово, в шаговой доступности несколько детских садов, две школы, множество различных магазинов, остановка общественного транспорта прямо на территории комплекса, детские площадки с игровыми зонами,",
  "town": "Cologne",
  "previewImage": "./markup/img/room.jpg",
  "houseImage": ["./markup/img/apartment-01.jpg",
      "./markup/img/apartment-02.jpg",
      "./markup/img/apartment-03.jpg",
      "./markup/img/studio-01.jpg",
      "./markup/img/room.jpg",
      "./markup/img/apartment-01.jpg"],
  "premium": true,
  "houseType": "room",
  "room": 5,
  "guest": 4,
  "price": 4000,
  "amenity": [
    "Laptop friendly workspace",
    "Baby seat",
    "Washer"
  ],
  "coordinatesTown":{
    "latitude": "48.85661",
    "longitude": "2.351499"
  }
}
###

#Update
PATCH http://localhost:4000/update/64a264ee3196e7a1a31d1120 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY0YTEzZWQ4ZDA0YjYxNzlhMmNmZDI3MSIsImVtYWlsIjoiMXRvcnRAZ21haWwuY29tIiwiaWF0IjoxNjg4MzUyOTI3LCJleHAiOjE2ODg1MjU3Mjd9.30aBkIT3Mkw-fPvMnEcMrl0YHHfOGih_ZQDk85NiU1I

{
  "offerName": "Сдам Дом уe Озера",
  "description": "GGОчень красивый Микрорайон Любимово, в шаговой доступности несколько детских садов, две школы, множество различных магазинов, остановка общественного транспорта прямо на территории комплекса, детские площадки с игровыми зонами,",
  "town": "Cologne",
  "previewImage": "./markup/img/room.jpg",
  "houseImage": ["./markup/img/apartment-01.jpg",
      "./markup/img/apartment-02.jpg",
      "./markup/img/apartment-03.jpg",
      "./markup/img/studio-01.jpg",
      "./markup/img/room.jpg",
      "./markup/img/apartment-01.jpg"],
  "premium": true,
  "houseType": "room",
  "room": 4,
  "guest": 3,
  "price": 12000,
  "amenity": [
    "Laptop friendly workspace",
    "Baby seat",
    "Washer"
  ],
  "coordinatesTown":{
    "latitude": "48.85661",
    "longitude": "2.351499"
  }
}

###

#Delete
DELETE  http://localhost:4000/delete/64a264ee3196e7a1a31d1120 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY0YTEzZWQ4ZDA0YjYxNzlhMmNmZDI3MSIsImVtYWlsIjoiMXRvcnRAZ21haWwuY29tIiwiaWF0IjoxNjg4MzUyOTI3LCJleHAiOjE2ODg1MjU3Mjd9.30aBkIT3Mkw-fPvMnEcMrl0YHHfOGih_ZQDk85NiU1I
###

## Отправка одной фотографии предложениея по аренде

POST http://localhost:4000/offers/64a23eb427c6a4e8e1550203/image HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY0YTEzZWQ4ZDA0YjYxNzlhMmNmZDI3MSIsImVtYWlsIjoiMXRvcnRAZ21haWwuY29tIiwiaWF0IjoxNjg4MzY2NDkwLCJleHAiOjE2ODg1MzkyOTB9.5_LNrIjO97mAtwqr_8SDKosTiyDwG3U-du9bPa3-vsI
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="previewImage"; filename="amsterdam.png"
Content-Type: image/png

< ./../../../../markup/img/amsterdam.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Отправка колекции фотографий предложениея по аренде

POST http://localhost:5000/offers/6492d52517d2e5a5496dfe22/pictures HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDkyZDQzNTE3ZDJlNWE1NDk2ZGZlMTgiLCJpYXQiOjE2ODczNDQyMTgsImV4cCI6MTY4NzUxNzAxOH0.Rwjez_RNPUL9PMBXjUTFP_MomLlxIJorCjDJLIb7M9M

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="houseImages"; filename="amsterdam.png"
Content-Type: image/png

< ./../../../../markup/img/amsterdam.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="houseImages"; filename="amsterdam.png"
Content-Type: image/png

< ./../../../../markup/img/amsterdam.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="houseImages"; filename="amsterdam.png"
Content-Type: image/png

< ./../../../../markup/img/amsterdam.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="houseImages"; filename="amsterdam.png"
Content-Type: image/png

< ./../../../../markup/img/amsterdam.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="houseImages"; filename="amsterdam.png"
Content-Type: image/png

< ./../../../../markup/img/amsterdam.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="houseImages"; filename="amsterdam.png"
Content-Type: image/png

< ./../../../../markup/img/amsterdam.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
