export const AppComponent = {
    RestApplication: Symbol.for('RestApplication'),
    LoggerInterface: Symbol.for('LoggerInterface'),
    ConfigInterface: Symbol.for('ConfigInterface'),
    DatabaseInterface: Symbol.for('DatabaseInterface'),
    UserServiceInterface: Symbol.for('UserServiceInterface'),
    UserModel: Symbol.for('UserModel'),
    OfferServiceInterface: Symbol.for('OfferServiceInterface'),
    OfferModel: Symbol.for('OfferModel'),
    CommentServiceInterface: Symbol.for('CommentServiceInterface'),
    CommentModel: Symbol.for('CommentModel'),
    CommentController: Symbol.for('CommentController'),
    ExceptionFilter: Symbol.for('ExceptionFilter'),
    UserController: Symbol.for('UserController'),
    OfferController: Symbol.for('OfferController'),
} as const;
